project:
  type: website
  output-dir: docs

website:
  title: "523 C"
  navbar:
    left:
      - lab-01.qmd
      - lab-02.qmd

format:
  html:
    theme: 
      light: sandstone
      dark: solar
    css: styles.css
    toc: true
    page-layout: full
