project:
  type: website
  output-dir: docs

website:
  title: "523 C"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - lab-01.qmd
      - lab-02.qmd

format:
  html:
    theme: 
      light: sandstone
    page-layout: full
